### ISSUE TITLE
Mnemonic Conflicts with 'OK, I have backed up' Button

### ISSUE THREAD

**Issue by deerwhisper2310** [Zero-1729/volt#5]
**Describe the problem**

The final row of the mnemonic (words 5 and 11) are partially hidden under the 'OK, I have backed up' button

**Describe the solution you'd like**

The 'OK, I have backed up' button could probably be moved down a bit, or the mnemonic words could be moved up

**Additional context**

Volt v0.4.3-beta.2
Pixel 6
GrapheneOS v2024053100

**Comment by Zero-1729** [comment]
Hi, thank you for flagging. I tried emulating the Pixel 6 on Android Studio and wasn't able to replicate the issue.

<img width="336" alt="Screenshot 2024-06-08 at 16 49 19" src="https://github.com/Zero-1729/volt/assets/23586626/61ac1bae-32df-470a-aa5e-ede6f4405cff">

Although Volt doesn't allow screenshots on Android, are you able to take a photo of how it's being rendered on your Pixel 6?

**Comment by Zero-1729** [comment]
Feel free to re-open if you are still seeing the issue and are able to post an image of your screen.

**Comment by deerwhisper2310** [comment]
![Screenshot_20240612-125704.png](https://github.com/Zero-1729/volt/assets/142937144/3e4f7a7f-bf19-44cb-bcee-98cec7efbeb0)

This is what it looks like on my end

**Comment by deerwhisper2310** [comment]
> Feel free to re-open if you are still seeing the issue and are able to post an image of your screen.

I dont believe I can reopen myself as I'm not a contributor to the repo.

**Comment by Zero-1729** [comment]
No problem, thanks again for reporting and the testing. It should be resolved in the v0.4.5-beta.1 update.
