### ISSUE TITLE
Bug report - Overlapping Menus

### ISSUE THREAD

**Issue by BigBossRabbit** [Zero-1729/volt#9]
Testing out Volt on the following Android Device:

```
- Device: Huawei P20
- Model: EML-L29
- EMUI version: 10.0.0
- Android version: 10
- Processor: HiSilicon Kirin 970

```
Initial installation went well without any problems. Used the provided volt-0.4.4.apk to install it
![IMG_2471](https://github.com/Zero-1729/volt/assets/87260669/ce87d15f-7317-4dd4-ab18-ffdac2ab8237)

This was the 1st overlap that I saw when clicking on the three dots (menu) in the top right of the screen & then clicking on the `Backup` option. The 4 circles run over the number 2. This happens in other screens asking for the pin as well but i don't have pics of them as well.
![IMG_2472](https://github.com/Zero-1729/volt/assets/87260669/f1159db1-accf-4c68-a648-08fc537c3bce)

When viewing your Mnemonic the 1st & 6th words are covered by the `Mnemonic | Descriptor` "switch box" which makes them illegible. 
![IMG_2473](https://github.com/Zero-1729/volt/assets/87260669/10ff11dd-1ef3-4f12-8fcc-0abfae70266b)

Same happens with the `Descriptor` option as the "switch box" runs over the top of the QR code.
![IMG_2474](https://github.com/Zero-1729/volt/assets/87260669/9548be32-6a24-47db-82c3-aacd40df228b)

`Additional Notes`

```
- When viewing your `xpub` there is no problem with the way it is displayed & nothing is blocking the QR code.
- When viewing your Backup via the actual `Backup` button, there is no problem with being able to view the entire Mnemonic Phrase
- I know it's probably on the roadmap already but can we please add as many African fiat currencies as possible to help erase the need for mental conversations into local fiat currencies? Will also help people know the app was made with them in mind.
```

Thank you for all the hard work you guys have put into this. Will be testing it our more & more over the rest of this month as my spending wallet.

**Comment by Zero-1729** [comment]
Hi @BigBossRabbit, thank you for the thorough testing and surfacing the overlapping issue! 

I'll go through each and adjust the styling for this screen size range. These changes will be reflected in the next version `v0.4.5-beta.1`.

RE currencies, correct, I'll be adding more African currencies for sure; depends on finding another source other than Coingecko to get those additional currencies.

**Comment by BigBossRabbit** [comment]
Hi @Zero-1729 many thanks for your reply & consideration of the above testing. 

Looking forward to fully utilizing  your project & introducing it to more people on my side of the continent. 

Will keep testing & report any other findings in the same manner 🫡

**Comment by Zero-1729** [comment]
Thanks again for reporting and the tests. Should be all good now in the v0.4.5-beta.1 update.
